version: "3.8"
services:
  database:
    image: 'postgres:bullseye'
    ports: # <Port in machine>:<port in container>
      - "5432:5432"
    env_file:
      - secrets.env
  tests:
    build: ./tests
    env_file:
      - secrets.env
    depends_on:
      - "database"
  weather:
    build: ./src/weather
    env_file:
      - secrets.env
    depends_on:
      - "database"
  create_database:
    build:
      context: .
      dockerfile: ./src/create_database/Dockerfile
    env_file:
      - secrets.env
    depends_on:
      - "database"
